### ISSUE TITLE
Add support for photos

### ISSUE THREAD

**Issue by Trulsaa** [Trulsaa/obsidian-icloud-contacts#10]
Needs auth header from existing calls. Try extending the iCloud client with a download photo function. Store the photos as attachmemts an link to them in the start of the note to get the picture on hover of a contact link.

**Comment by Trulsaa** [comment]
Unable to find cookies in the responses from the API that could be used to fetch photos.

**Comment by Trulsaa** [comment]
Will close this issue until someone expresses a need for it.

**Comment by Trulsaa** [comment]
> Would love to have this feature, Let me know in anyway I can help.

I would also love to have this feature. Any help on how to authenticate with the photo api would be much appreciated.

**Comment by VSuryaPrashanth** [comment]
I will try to look into it, but please don't expect anything soon, as I might be a bit busy for a while.

**Comment by Trulsaa** [comment]
> I will try to look into it, but please don't expect anything soon, as I might be a bit busy for a while.

Take all the time you need
