### ISSUE TITLE
Custom Frontmatter Fields

### ISSUE THREAD

**Issue by kennygokh** [Trulsaa/obsidian-icloud-contacts#12]
Hi, it will be good that I can have a way to add my custom frontmatter field. A way of template that can allow me to add my custom frontmatter field without interrupting the icloud contacts fields. For example, I have CreatedDate field to store created date & time, Status field, I used this field to filter any notes that are not Active etc.

**Comment by Trulsaa** [comment]
That is a good future request. Thank you!

To be sure I understand what you mean. Do you mean: When the plugin updates it should keep your custom frontmatter and not overwrite or remove them?

**Comment by Trulsaa** [comment]
Depends on #5

**Comment by Trulsaa** [comment]
Version 0.3.0 was just released. This version enables you to add custom frontmatter fields. You can add your own properties to the frontmatter. The plugin will only manage the following property keys: name, organization, departement, telephone, email, url, related names, instant message, social profile, date, birthday pluss any of the kays you remove from the excluded keys setting. Please test it out and give feedback on how it works for you.
