### ISSUE TITLE
Allow to use templates for the contact

### ISSUE THREAD

**Issue by connradolisboa** [Trulsaa/obsidian-icloud-contacts#22]
Allow to use a template for the contacts with {{value}} type syntax. Ability to add or remove properties from the contact.

**Comment by Trulsaa** [comment]
I am a bit unsure what you mean. Do you mean a setting that points to a templet for the frontmatter?

It is already possible to remove properties from the contact. You can you the Excluded keys setting. For example if you would like to remove the email property from all contact, you can add email to the Excluded keys setting string.

I know this setting might not be that intuitive to use. But it works for my use case. I would be happy to consider a better solution if you have suggestions ore can provide me with your use case.

**Comment by Trulsaa** [comment]
Feel free to reopen if new info comes to light.
