### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Lmasey** [Trulsaa/obsidian-icloud-contacts#24]
I could have messed something up, but I received this message 

Request failed. The operation couldn’t be completed. (NSURLErrorDomain error -1012.)

How do I fix it?

**Comment by Trulsaa** [comment]
I have not seen this error before. Looks like something in the network. Are you able to provide some more information of how to recreate this issue?

**Comment by Trulsaa** [comment]
Closed because unable to reproduce. Please reopen if new information is available.
