### ISSUE TITLE
Not all contacts are synced

### ISSUE THREAD

**Issue by Andrei-Ioda** [Trulsaa/obsidian-icloud-contacts#25]
I have 760 contacts in my iCloud. After sync i see 258 in Obsidian only. No errors. 

I deleted all synced contacts and tried sync again. Nothing changed - 258 contacts only.

**Comment by Trulsaa** [comment]
Did you resently add your contacts to the ocloud account? I have had similar problems after deleting all my contacts in icloud and then adding them aggain. Its as if there is some delay with sync between the icloud database I uploud to and the one used to download from.

**Comment by Andrei-Ioda** [comment]
I solved the problem by checking my contacts. There were duplicates. Perhaps this solved the synchronization problem.
But I recently got a new error.
I get an error when syncing (see attached screenshot).
And empty contact is created in the contacts folder - .md

![Screenshot 2024-06-01 at 12 00 10@2x](https://github.com/Trulsaa/obsidian-icloud-contacts/assets/50438842/428bdef3-5db4-4a25-82c6-f03b77c335ac)

**Comment by Trulsaa** [comment]
> I solved the problem by checking my contacts. There were duplicates. Perhaps this solved the synchronization problem.
> 
> But I recently got a new error.
> 
> I get an error when syncing (see attached screenshot). And now i get this error every sync.
> 
> And empty contact is created in the contacts folder - .md
> 
> 
> 
> ![Screenshot 2024-06-01 at 12 00 10@2x](https://github.com/Trulsaa/obsidian-icloud-contacts/assets/50438842/428bdef3-5db4-4a25-82c6-f03b77c335ac)
> 
> 

How many duplicates did you have of any single contact? The newest version of this plugin is supposed to handle duplicates by creating the with an appended ascending number. Did you experience any error messages?

I created a new issue with your new error and answered there to make it easier for others with the same issue to find it. Thank you for reporting it. https://github.com/Trulsaa/obsidian-icloud-contacts/issues/26.

**Comment by Trulsaa** [comment]
Closed because unable to reproduce. Please reopen if new information is available.

**Comment by Andrei-Ioda** [comment]
I don't remember how many duplicated contacts I had. I went through everyone's contact list and deleted duplicates. After which the synchronization started working. Before that, it stopped at some kind of contact.
