### ISSUE TITLE
Empty contact is created in the contacts folder - .md

### ISSUE THREAD

**Issue by Trulsaa** [Trulsaa/obsidian-icloud-contacts#26]
I solved the problem by checking my contacts. There were duplicates. Perhaps this solved the synchronization problem.
But I recently got a new error.
I get an error when syncing (see attached screenshot). And now i get this error every sync.
And empty contact is created in the contacts folder - .md

![Screenshot 2024-06-01 at 12 00 10@2x](https://github.com/Trulsaa/obsidian-icloud-contacts/assets/50438842/428bdef3-5db4-4a25-82c6-f03b77c335ac)

_Originally posted by @Andrei-Ioda in https://github.com/Trulsaa/obsidian-icloud-contacts/issues/25#issuecomment-2143332710_

**Comment by Trulsaa** [comment]
I have gotten this error when I have a contact without a name. I can se from the error that the contact that is being synced has no name. Se `\nN:;;;;;` in the data. I can have a look at the code and see if this situation can be handled more gracefully. In the meantime you can try to find the contact "No Name" among your contacts and delete or give a name.

**Comment by Andrei-Ioda** [comment]
Thank you. After deleting an empty contact, I no longer receive the error.
