### ISSUE TITLE
please support chinese user

### ISSUE THREAD

**Issue by isdamir** [Trulsaa/obsidian-icloud-contacts#28]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/16e1f7f8-5ff0-4b70-a63b-1322299731b0">
Due to the independent nature of iCloud in China, the default server address is unavailable. It would be helpful to add a region selection feature to switch addresses. The server address for China is: https://contacts.icloud.com.cn/

**Comment by Trulsaa** [comment]
I added support for different serverUrls through settings and deployed a new version. Does this fix your issue?
