### ISSUE TITLE
Filter contacts

### ISSUE THREAD

**Issue by ThomSMG** [Trulsaa/obsidian-icloud-contacts#29]
Would it be possible to add a filter criteria for the contacts to be synced or not? E.g. by property-name and a regex. My use case is that i have a vault for work and another for personal stuff. each references different persons.

**Comment by Trulsaa** [comment]
A filter criteria would be possible with some work.

I have the same issue that i solve by having two icloud accounts. That way I can sync one icloud account to each vault. And in the contacts app I can drag and drop to choose what contact is in each account or both. Maybe that would work for you to?

**Comment by ThomSMG** [comment]
Hi @Trulsaa ! Thanks for your work on the plugin in the first place :) interesting option, will consider it .

**Comment by Trulsaa** [comment]
Thank you for giving feedback. Let me know how it goes.
